In [ ]:
import numpy as np
#2D
np.array([[4,4,5],[7,6,4],[9,7,4],[6,3,7]])


array([[4, 4, 5],
       [7, 6, 4],
       [9, 7, 4],
       [6, 3, 7]])

In [ ]:
#3D
np.array ([[[7,8,5],[4,7,7],[7,1,9],[5,4,10]],[[2,1,2],[9,8,5],[3,7,3],[4,9,9]],[[2,9,3],[2,4,8],[1,6,6],[8,1,3]]])

array([[[ 7,  8,  5],
        [ 4,  7,  7],
        [ 7,  1,  9],
        [ 5,  4, 10]],

       [[ 2,  1,  2],
        [ 9,  8,  5],
        [ 3,  7,  3],
        [ 4,  9,  9]],

       [[ 2,  9,  3],
        [ 2,  4,  8],
        [ 1,  6,  6],
        [ 8,  1,  3]]])

In [ ]:
#Menambah angka
a=np.array ([[1,8,8,2],[8,2,1,2],[10,1,4,7],[1,4,7,8],[8,2,3,4]])
print("array awal")
print(a)
a[1:4:2, 0:4] = a[1:4:2, 0:4]+1
print("baris ganjil +1")
print(a)
a[0:4, 0:4:2] = a[0:4, 0:4:2]+2
print("kolom genap  +2")
print(a)

array awal
[[ 1  8  8  2]
 [ 8  2  1  2]
 [10  1  4  7]
 [ 1  4  7  8]
 [ 8  2  3  4]]
baris ganjil +1
[[ 1  8  8  2]
 [ 9  3  2  3]
 [10  1  4  7]
 [ 2  5  8  9]
 [ 8  2  3  4]]
kolom genap  +2
[[ 3  8 10  2]
 [11  3  4  3]
 [12  1  6  7]
 [ 4  5 10  9]
 [ 8  2  3  4]]


In [ ]:
#Balik sumbu z
a=np.array([[[7,8,5],[4,7,7],[7,1,9],[5,4,10]],[[2,1,2],[9,8,5],[3,7,3],[4,9,9]],[[2,9,3],[2,4,8],[1,6,6],[8,1,3]]])

a=np.array_split(a,3)
a=np.concatenate((a[2],a[1],a[0]))
print(a)

[[[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]]


In [ ]:
#6x6 array
a = np.array([7,8,5,4,7,7,7,1,9,5,4,10,2,1,2,9,8,5,3,7,3,4,9,9,2,9,3,2,4,8,1,6,6,8,1,3])
np.reshape(a,(6,6))

array([[ 7,  8,  5,  4,  7,  7],
       [ 7,  1,  9,  5,  4, 10],
       [ 2,  1,  2,  9,  8,  5],
       [ 3,  7,  3,  4,  9,  9],
       [ 2,  9,  3,  2,  4,  8],
       [ 1,  6,  6,  8,  1,  3]])

In [ ]:
a=np.array([[[5,10,10,7],[7,8,4,10],[9,10,2,5],[1,8,9,3],[6,10,5,2],[4,6,9,4],[,1,9],[5,4,10]]]]])